language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  keep-history: true
  on:
    branch: source
before_script:
  - "npm i"
script:
  - "npm run build"
