language: node_js
node_js:
  - "stable"
dist: xenial
os:
  - "linux"
deploy:
  strategy: git
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  keep_history: true
  on:
    branch: source
before_script:
  - "npm i"
script:
  - "npm run build"
