language: node_js
os:
  - "linux"
dist: xenial
node_js:
  - "stable"
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  keep_history: true
  on:
    branch: source
before_script:
  - "npm i"
script:
  - "npm run build"
